### ISSUE TITLE
Issue With EJS

### ISSUE THREAD

**Issue by emmadema** [emmadema/Project-2#2]
Im having an issue with the EJS for my form. I keep getting the same error and Im having toruble understanding why:
ReferenceError: /Users/emmademango/Desktop/wdi-work/project-2/views/addClothing.ejs:57
    55|       <div>
    56|         
 >> 57|         <h1><%= typeOf %></h1>
    58|         <ul>
    59|           <li><%= season %></li>
    60|           <li><%= color %></li>

typeOf is not defined

It seems like I am doing something incorrectly with my addClothing.ejs.
Are there any other good EJS form submit labs to reference? I have tried: tunely, into to EJS and book-app. Please let me know, I feel like Im just missing something small.

**Comment by nickandersonr** [comment]
It's DB seed error - close out when you get a chance!
