### ISSUE TITLE
Yes This is My Third Issue

### ISSUE THREAD

**Issue by emmadema** [emmadema/Project-2#3]
Hi again. I am trying to get my form data to append to the page and I am getting it .. sort of, but its not in the right place. Is this and EJS error or a route error or both? Or none. I'm confused. I keep changing things, but have not been successful. 

Also I am having some API issues with getting specific data instead of the whole thing. Is there a good lesson to reference for this?

**Comment by ZebGirouard** [comment]
Definitely on the right track, great work Emma!
